#!/usr/bin/env bash
# Open (or prepare) a Grok Build TUI bound to an existing ticket worktree.
#
# Usage:
#   open-grok-worktree.sh <worktree-path> [branch-name]
#   open-grok-worktree.sh --write-only <worktree-path> [branch-name]
#
# --write-only  only write <worktree>/.grok-session.sh (do not exec grok)
# Default       write launcher, then exec: grok --cwd <worktree>
#
# Does NOT create git worktrees. Use the ticket-worktree skill for that.
# Does NOT use `grok --worktree=` (that creates a new Grok-managed tree).

set -euo pipefail

WRITE_ONLY=0
if [[ "${1:-}" == "--write-only" ]]; then
  WRITE_ONLY=1
  shift
fi

WT="${1:-}"
BRANCH="${2:-}"

if [[ -z "$WT" ]]; then
  echo "Usage: $0 [--write-only] <worktree-path> [branch-name]" >&2
  exit 2
fi

if [[ ! -d "$WT" ]]; then
  echo "error: not a directory: $WT" >&2
  exit 1
fi

WT="$(cd "$WT" && pwd)"

if [[ -z "$BRANCH" ]]; then
  if git -C "$WT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    BRANCH="$(git -C "$WT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
  fi
fi
BRANCH="${BRANCH:-unknown-branch}"

LAUNCHER="$WT/.grok-session.sh"
cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Local launcher for this ticket worktree (not committed).
# Generated by ticket-worktree open-grok-worktree.sh
set -euo pipefail
cd "$WT"
echo "Grok session cwd: $WT"
echo "Expected branch:  $BRANCH"
echo "Header should show: $BRANCH   $WT"
exec grok --cwd "$WT" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "Wrote $LAUNCHER"
echo
echo "Open implement session (correct branch/cwd header):"
echo "  $LAUNCHER"
echo "  # or:  grok --cwd $WT"
echo "  # then: /rename $BRANCH"
echo

if [[ "$WRITE_ONLY" -eq 1 ]]; then
  exit 0
fi

exec grok --cwd "$WT"
